version: 2.1

jobs:
  build-frontend:
    docker:
      - image: cimg/node:14.4.0
    steps:
      - checkout
      - run:
          name: build frontend
          command: |
            cd newsily
            npm install
            npm build
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-build

  test-frontend:
    docker:
      - image: cimg/node:14.4.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Test frontend 
          shell: /bin/bash
          command: |
            cd newsily
            npm install 
            npm test 

  scan-frontend:
    docker:
      - image: cimg/node:14.4.0
    steps:
      - checkout 
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: scan frontend with hadolint
          command: |
            cd newsily
            npm install 
            docker run --rm -i hadolint/hadolint < Dockerfile

  scan-backend:
    docker:
      - image: 
    steps:
      - checkout
    run:
      name: Scan backend with hadolint 
      command: |
        cd newsily-backend
        docker run --rm -i hadolint/hadolint < Dockerfile


workflows:
  complete-autodeploy:
    jobs:
      - build-frontend
      - test-frontend:
          requires: [build-frontend]
      - scan-frontend
      - scan-backend
