version: 2.1

jobs:
  build-frontend:
    docker:
      - image: cimg/node:14.4.0
    steps:
      - checkout
      - run:
          name: build frontend
          command: |
            cd newsily
            npm install
            npm build
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-build

  test-frontend:
    docker:
      - image: cimg/node:14.4.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Test frontend 
          command: |
            cd frontend
            npm install 
            npm test 


workflows:
  complete-autodeploy:
    jobs:
      - build-frontend
