version: 2.1

jobs:
  build-frontend:
    docker:
      - image: cimg/node:18.7.0
    steps:
      - checkout
      - run:
          name: build frontend
          command: |
            cd newsily
            npm install
            npm run build

workflows:
  complete-autodeploy:
    jobs:
      - build-frontend
