# Generated by Django 3.2 on 2021-04-12 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('general', 'general'), ('finance', 'Finance'), ('sports', 'Sports')], default='general', max_length=10)),
                ('description', models.TextField(max_length=1000)),
                ('logo', models.URLField()),
                ('website', models.URLField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_ref', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('description', models.CharField(default='description', max_length=255)),
                ('date_of_subscription', models.DateTimeField(default=django.utils.timezone.now)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='subscriptions.subscriptions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date_of_subscription', 'user'),
            },
        ),
    ]
