# Generated by Django 3.2 on 2021-04-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='background_image',
            field=models.URLField(default='https://img'),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('finance', 'Finance'), ('sports', 'Sports')], default='general', max_length=10),
        ),
    ]
