# Generated by Django 3.2.9 on 2022-06-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreRequestInfoInEpoch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epoch_time', models.BigIntegerField()),
                ('request_info', models.TextField()),
            ],
        ),
    ]
